#!/system/bin/sh
#
# Script to make boot animations work
#

# Remove current binary
rm -f /system/bin/samsungani

# If a custom bootanimation.zip file is present, we will use it. The binary
# file needs to be named samsungani or else it will never be killed by the
# system and the animation keeps looping.
if ls /system/media/bootanimation.zip
then
	cp -f /system/bin/bootanimation /system/bin/samsungani
else
	cp -f /system/bin/samsung /system/bin/samsungani
fi

# make /system r/o again
mount -o remount,ro /dev/block/stl10 /system
