#!/sbin/sh
#
# Odin builder script
#
# This script is meant to create a fully working Odin backup of your device.
# The script will not currently auto-detect partitions for the device to be
# dumped, and everything is statically linked. If you wish to use this for a
# device outside of the DROID Charge, please be aware of this and modify the
# device nodes accordingly.
#
# Originally written by imnuts (Mark Dietz)

# Notify that it will take a little bit
echo "Creating an Odin backup. This will take a few minutes"

# Setup variables
DATE=$(date +%m%d%Y%H%M)
SYSTEM="/dev/block/stl10"
DATA="/dev/block/mmcblk0p1"
DBDATA="/dev/block/stl11"
KERNEL="/dev/block/bml8"
RECOVERY="/dev/block/bml9"

# output files on the SDCard
cd /sdcard

# Dump files
# /system
echo "Dumping /system..."
dd if="$SYSTEM" of=factoryfs.rfs bs=4096 > /dev/null
# /data
echo "Dumping /data..."
dd if="$DATA" of=movinand.bin bs=4096 > /dev/null
# /dbdata
echo "Dumping /dbdata..."
dd if="$DBDATA" of=dbdata.rfs bs=4096 > /dev/null
# kernel
echo "Dumping kernel..."
dd if="$KERNEL" of=zImage bs=4096 > /dev/null
# recovery
echo "Dumping recovery..."
dd if="$RECOVERY" of=recovery.bin bs=4096 > /dev/null
echo "Done dumping files..."

# Create Odin package
echo "Creating Odin package..."
tar -c dbdata.rfs factoryfs.rfs movinand.bin recovery.bin zImage > "$DATE".tar > /dev/null
md5sum -t "$DATE".tar >> "$DATE".tar > /dev/null
mv "$DATE".tar "$DATE".tar.md5 > /dev/null

# Clean up and remove files
rm -f dbdata.rfs factoryfs.rfs movinand.bin recovery.bin zImage > /dev/null

# Done
echo "Done creating Odin package..."
echo ""
echo "Odin file is located at /sdcard/$DATE.tar.md5"
